version: '3.7'

services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - ./docker-volumes/mongodb:/data/db

  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123
    volumes:
      - ./docker-volumes/redis:/data